### ISSUE TITLE
Please add description of solution in readme

### ISSUE THREAD

**Issue by mi-hol** [timg236/rpi-system-update#1]
Hi Tim,

it seems you are developing a great solution.
Would you mind to share a general description regarding scope of planned solution to readme?

**Comment by timg236** [comment]
Added a link to the readme to the full documentation
 https://github.com/timg236/buildroot/blob/raspberrypi-system-update-buildroot-2022.08/raspberrypi-system-update.md

It's example code but should be something that anyone can build and run themselves and see how things like tryboot and secure-boot work. So, not something to use directly but if there's useful bits to upstream into buildroot or elsewhere than that would be a good result.
